# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0006_auto_20160323_1539'),
    ]

    operations = [
    ]
