# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waypoints', '0026_auto_20160322_1855'),
    ]

    operations = [
    ]
