# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0002_auto_20160323_1141'),
    ]

    operations = [
    ]
