# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0003_auto_20160323_1332'),
    ]

    operations = [
    ]
