# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0009_auto_20160323_1751'),
    ]

    operations = [
    ]
