# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findme', '0011_auto_20160323_1754'),
    ]

    operations = [
    ]
