# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 14:44
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='waypoint',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='address',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='city',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='longitude',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='altitudemode',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='begin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 27, 14, 44, 48, 140558, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='draworder',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 27, 14, 44, 48, 140575, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='extrude',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='icon',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='tessellate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 4, 27, 14, 44, 48, 140534, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='visibility',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
