# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 09:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_tra', models.CharField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('ref', models.CharField(blank=True, max_length=254)),
                ('route_ref', models.CharField(blank=True, max_length=254)),
                ('operator', models.CharField(blank=True, max_length=254)),
                ('network', models.CharField(blank=True, max_length=254)),
                ('train', models.CharField(blank=True, max_length=254)),
                ('subway', models.CharField(blank=True, max_length=254)),
                ('monorail', models.CharField(blank=True, max_length=254)),
                ('tram', models.CharField(blank=True, max_length=254)),
                ('bus', models.CharField(blank=True, max_length=254)),
                ('trolleybus', models.CharField(blank=True, max_length=254)),
                ('aerialway', models.CharField(blank=True, max_length=254)),
                ('ferry', models.CharField(blank=True, max_length=254)),
                ('shelter', models.CharField(blank=True, max_length=254)),
                ('bench', models.CharField(blank=True, max_length=254)),
                ('covered', models.CharField(blank=True, max_length=254)),
                ('area', models.CharField(blank=True, max_length=254)),
                ('z_order', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857)),
                ('area_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='area_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_comment', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_comments', to='transport.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_tra', models.CharField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('ref', models.CharField(blank=True, max_length=254)),
                ('route_ref', models.CharField(blank=True, max_length=254)),
                ('operator', models.CharField(blank=True, max_length=254)),
                ('network', models.CharField(blank=True, max_length=254)),
                ('train', models.CharField(blank=True, max_length=254)),
                ('subway', models.CharField(blank=True, max_length=254)),
                ('monorail', models.CharField(blank=True, max_length=254)),
                ('tram', models.CharField(blank=True, max_length=254)),
                ('bus', models.CharField(blank=True, max_length=254)),
                ('trolleybus', models.CharField(blank=True, max_length=254)),
                ('aerialway', models.CharField(blank=True, max_length=254)),
                ('ferry', models.CharField(blank=True, max_length=254)),
                ('shelter', models.CharField(blank=True, max_length=254)),
                ('bench', models.CharField(blank=True, max_length=254)),
                ('covered', models.CharField(blank=True, max_length=254)),
                ('area', models.CharField(blank=True, max_length=254)),
                ('z_order', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=3857)),
                ('route_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Poly',
        ),
        migrations.AlterModelManagers(
            name='waypoint',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='address',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='city',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='longitude',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='aerialway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='area',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='audio_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='audio_talking_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='bench',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='bus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='coffee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='ferry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=3857),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='indicator',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='level_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='monorail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='network',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='operator',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='public_tra',
            field=models.CharField(default=b'stop_position', max_length=254),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='ramp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='ref',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='route_ref',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='shelter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='steps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='subway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='train',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='tram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='trolleybus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='wp_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wp_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='z_order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(default=b'', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='waypoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wp_comments', to='transport.Waypoint'),
        ),
    ]
