# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 17:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20160427_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.FloatField(blank=True, null=True)),
                ('public_tra', models.CharField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('ref', models.CharField(blank=True, max_length=254)),
                ('route_ref', models.CharField(blank=True, max_length=254)),
                ('operator', models.CharField(blank=True, max_length=254)),
                ('network', models.CharField(blank=True, max_length=254)),
                ('train', models.CharField(blank=True, max_length=254)),
                ('subway', models.CharField(blank=True, max_length=254)),
                ('monorail', models.CharField(blank=True, max_length=254)),
                ('tram', models.CharField(blank=True, max_length=254)),
                ('bus', models.CharField(blank=True, max_length=254)),
                ('trolleybus', models.CharField(blank=True, max_length=254)),
                ('aerialway', models.CharField(blank=True, max_length=254)),
                ('ferry', models.CharField(blank=True, max_length=254)),
                ('shelter', models.CharField(blank=True, max_length=254)),
                ('bench', models.CharField(blank=True, max_length=254)),
                ('covered', models.CharField(blank=True, max_length=254)),
                ('area', models.CharField(blank=True, max_length=254)),
                ('z_order', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.FloatField(blank=True, null=True)),
                ('public_tra', models.CharField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=254)),
                ('ref', models.CharField(blank=True, max_length=254)),
                ('route_ref', models.CharField(blank=True, max_length=254)),
                ('operator', models.CharField(blank=True, max_length=254)),
                ('network', models.CharField(blank=True, max_length=254)),
                ('train', models.CharField(blank=True, max_length=254)),
                ('subway', models.CharField(blank=True, max_length=254)),
                ('monorail', models.CharField(blank=True, max_length=254)),
                ('tram', models.CharField(blank=True, max_length=254)),
                ('bus', models.CharField(blank=True, max_length=254)),
                ('trolleybus', models.CharField(blank=True, max_length=254)),
                ('aerialway', models.CharField(blank=True, max_length=254)),
                ('ferry', models.CharField(blank=True, max_length=254)),
                ('shelter', models.CharField(blank=True, max_length=254)),
                ('bench', models.CharField(blank=True, max_length=254)),
                ('covered', models.CharField(blank=True, max_length=254)),
                ('area', models.CharField(blank=True, max_length=254)),
                ('z_order', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=3857)),
            ],
        ),
        migrations.DeleteModel(
            name='Poly',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='altitudemode',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='draworder',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='end',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='extrude',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='tessellate',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='waypoint',
            name='visibility',
        ),
        migrations.AddField(
            model_name='waypoint',
            name='aerialway',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='area',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='bench',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='bus',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='covered',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='ferry',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='indicator',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='monorail',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='network',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='operator',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='osm_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='public_tra',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='ref',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='route_ref',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='shelter',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='subway',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='train',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='tram',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='trolleybus',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='z_order',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=3857),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
