# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import gatekeeper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(default=b'', max_length=254, unique=True, verbose_name=b'email address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last Name')),
                ('homepage', models.URLField(blank=True, default=b'')),
                ('picture', models.ImageField(blank=True, default=b'avatars/default/woman.jpg', null=True, upload_to=gatekeeper.models.Avatar_User_Dir())),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=gatekeeper.models.Avatar_User_Dir())),
                ('latitude', models.DecimalField(decimal_places=6, default=b'53.458202', max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, default=b'-2.498955', max_digits=10, null=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='admin status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
