# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 07:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import gatekeeper.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=gatekeeper.models.Avatar_User_Dir()),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='homepage',
            field=models.URLField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=gatekeeper.models.Avatar_User_Dir()),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='username'),
        ),
    ]
