# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatekeeper', '0002_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=b'53.485900', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=b'-2.232000', max_digits=10, null=True),
        ),
    ]
